apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-go-basic-oh7u
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/test-rhtap-72-tenant/load-app-36929988-5ed2-4a5f-aa2e-3c57736ff459/devfile-sample-go-basic-oh7u@sha256:4cd49ea0449c2ad7e6391419c1ee77e15ed3e16bb259cdf5fd21477d4d835ddf
        name: my-go
        resources: {}
status: {}
