apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-go-basic-oh7u
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-go-basic-oh7u
    app.kubernetes.io/part-of: load-app-36929988-5ed2-4a5f-aa2e-3c57736ff459
  name: devfile-sample-go-basic-oipfg
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: devfile-sample-go-basic-oh7u
    weight: null
status: {}
